FROM apache/superset:3.1.0

# Pindah ke user root sementara untuk install library
USER root

# Install driver ClickHouse untuk Superset
RUN pip install clickhouse-connect

# Kembali ke user superset
USER superset
