FROM apache/superset:6.0.0

# Pindah ke user root sementara untuk install library
USER root

# Install driver ClickHouse ke dalam virtual environment Superset
RUN pip install --target=/app/.venv/lib/python3.10/site-packages clickhouse-connect

# Kembali ke user superset      
USER superset
