services:
  # Source Database (Transactional)
  postgres-source:
    image: postgres:16-alpine
    container_name: postgres-source
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=5
      - -c
      - max_wal_senders=5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Message Broker (Redpanda)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
        internal://redpanda:9092,external://localhost:19092

    volumes:
      - redpanda_data:/var/lib/redpanda/data
    ports:
      - "19092:19092"
    networks:
      - default
      - observability

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.4.3
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    ports:
      - "8888:8080"
    depends_on:
      - redpanda

  # Order Service (FastAPI)
  order-service:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-source:5432/${POSTGRES_DB}
    volumes:
      - ../../services/order-service:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres-source:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  # Pelahap WAL CDC (Golang Ingestor)
  cdc-ingestor:
    build:
      context: ../../services/cdc-ingestor
      dockerfile: Dockerfile
    container_name: cdc-ingestor
    env_file:
      - ../../.env
    environment:
      - REDPANDA_BROKERS=redpanda:9092
    depends_on:
      postgres-source:
        condition: service_healthy
      redpanda:
        condition: service_started
    restart: on-failure
    networks:
      - default
    # Robot Transaksi (Traffic Generator)
  traffic-generator:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: traffic-generator
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-source:5432/${POSTGRES_DB}
      PYTHONUNBUFFERED: 1
    command: ["python", "data_generator.py", "--traffic"]
    depends_on:
      order-service:
        condition: service_healthy
    networks:
      - default
    restart: unless-stopped

  # Data Warehouse (ClickHouse)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP Interface (bisa dipakai untuk integrasi aplikasi)
      - "9000:9000" # Native Client (untuk DBeaver / ClickHouse CLI)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ../../services/cdc-ingestor/proto:/var/lib/clickhouse/format_schemas
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.d/users.xml
    networks:
      - default

  # ==========================================
  # BI / VISUALIZATION LAYER
  # ==========================================
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "my_very_secret_key_for_this_project"
      SUPERSET_LOAD_EXAMPLES: "no"
    depends_on:
      - clickhouse
    networks:
      - default
    volumes:
      - superset_home:/app/superset_home
      - ./dashboards:/app/dashboards

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../../services/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../services/grafana/provisioning:/etc/grafana/provisioning
      - ../../services/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - observability

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - /:/host:ro,rslave
    networks:
      - observability

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-source:5432/${POSTGRES_DB}?sslmode=disable"
    command:
      - "--collector.long_running_transactions"
      - "--collector.stat_wal_receiver"
    ports:
      - "9187:9187"
    networks:
      - default
      - observability
    depends_on:
      postgres-source:
        condition: service_healthy

volumes:
  postgres_data:
  superset_home:
  grafana-data:
  redpanda_data:
  clickhouse_data:

networks:
  observability:
    driver: bridge
